apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloud-mining-backend-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims", "services"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: ["traefik.containo.us"]
  resources: ["ingressroutetcps"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-mining-backend-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: cloud-mining-backend-sa
  namespace: default
roleRef:
  kind: Role
  name: cloud-mining-backend-role
  apiGroup: rbac.authorization.k8s.io
