apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-ingressroute-tcp-manager-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: cloud-mining-backend-sa
  namespace: default
roleRef:
  kind: Role
  name: traefik-ingressroute-tcp-manager
  apiGroup: rbac.authorization.k8s.io
