apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: traefik-ingressroute-tcp-manager
  namespace: default
rules:
- apiGroups: ["traefik.containo.us"]
  resources: ["ingressroutetcps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
