# cloud-mining-backend-serviceaccount.yaml
# Creates a ServiceAccount for the backend app to use with RBAC permissions

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-mining-backend-sa
  namespace: default
