# Binds the PVC Role to the backend ServiceAccount

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-mining-backend-pvc-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: cloud-mining-backend-sa
    namespace: default
roleRef:
  kind: Role
  name: cloud-mining-backend-pvc-role
  apiGroup: rbac.authorization.k8s.io