# Role for managing PersistentVolumeClaims (PVCs)

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloud-mining-backend-pvc-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]